# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  containers:
  - container: pcf-ops
    image: engineerbetter/pcf-ops:latest

variables:
- group: aws-terraform-secrets
- name: region
  value: eu-west-2
- name: state_file_path
  value: terraform.tfstate
- name: state_bucket
  value: azure-devops-training-will

pool:
  vmImage: ubuntu-latest

steps:
- script: $(Build.SourcesDirectory)/create-stuff.sh
  env:
    AWS_ACCESS_KEY_ID: $(aws-access-key-id)
    AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
    STATE_BUCKET: $(state_bucket)
    STATE_FILE_PATH: $(state_file_path)
    TF_VAR_region: $(region)
  target: pcf-ops