# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  containers:
  - container: terraform
    image: hashicorp/terraform:latest
    options: --entrypoint sh

variables:
- group: aws-terraform-secrets
- name: region
  value: eu-west-3
- name: state_file_path
  value: terraform.tfstate
- name: state_bucket
  value: azure-devops-training-will

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Here's the script starting"
  target: terraform